default_language_version:
  python: python3.10


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: check-added-large-files

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system
        stages: [commit, push]
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py38-plus
        types: [python]
        language: system
        stages: [commit, push]
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system
        stages: [commit, push]
      - id: ruff
        name: ruf
        entry: poetry run ruff check --config pyproject.toml
        types: [python]
        language: system
        stages: [commit, push]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        require_serial: true
        types: [python]
        language: system
        stages: [push]
      - id: gitleaks
        name: gitleaks
        entry: make gitleaks
        require_serial: true
        types: [file]
        language: system
        pass_filenames: false
        stages: [push]
